### ISSUE TITLE
Sequence of commands throws exit -11

### ISSUE THREAD

**Issue by tami2293** [spel-uchile/SUCHAI-Flight-Software#12]
The sequence of commands is:

"gssb_pwr -3939704102564418991  5869781495315577964 4 7253250973193467282 72641676938523946195919586611020448663 92095852830421742"

"obc_get_tle 16793979699593080985 17857068573924393177 10322398680214003687 Or_J&* 192257590 250513719604684287491227831468642555152 7894739251394641014 8707923985211518596 A'k;H"

"obc_get_tle params": "2004194787"

"drp_add_hrs_alive 3127852952733958122 9391651738274219152 -979119932 7231170491688674323 -489433029 4482114832065666601 63388019059325091875233039272059300098 "

"obc_set_tle 14411003027049097651  C== 2344406868469659858"

"com_send_tc 314106718 EH8 -1694651545 7341018154555866319 -4882686391962200564  775208981"

 "com_set_node -1865028106 1687056686716975758 -3538630954116661940 867883283 l0Y99yH\\vi 643596633 5388925920445264797 -84075540 2857361756551372032"

"fp_test_params"

 "fp_del_cmd_unix 6442240141094730330 7545538707934846397"

"fp_reset V2% -280075423304112696701987095457908484966 -49831311687398385273978517385574318196 48478279 1031446878426546993 10079855211877668909 4151605445481177871 350623479 334702254052999802426606103352297202003"

**Comment by carlgonz** [comment]
@tami2293 fp_test_params
[INFO ][1592580071][Executer] Running the command: fp_test_params...

Signal: SIGSEGV (Segmentation fault)

**Comment by carlgonz** [comment]
@carlgonz Close #12
