### ISSUE TITLE
Memory leaks detected in flight plan

### ISSUE THREAD

**Issue by carlgonz** [spel-uchile/SUCHAI-Flight-Software#2]
Commit 3ebf434800b4f4496784d922d4b5c4f39c8b6e20 reports several memory leak detected in the taskFlightPlan and data_storage module. Please fix.

**Comment by carlgonz** [comment]
Here is the Valgrind report obtained with CLion: `run->run <project> with Valgrind Memcheck`

![valdgrind_20180518_110956](https://user-images.githubusercontent.com/1055112/40243418-301675d0-5a8e-11e8-8dfe-829bd0abb43c.png)
![valgrind_20180518_111032](https://user-images.githubusercontent.com/1055112/40243421-323d83a8-5a8e-11e8-917e-df9b25847431.png)
![valgrind_20180518_111107](https://user-images.githubusercontent.com/1055112/40243426-34bbf286-5a8e-11e8-81f1-00cd3329c982.png)

**Comment by Grynn01** [comment]
Fixed
