### ISSUE TITLE
Command fp_del_cmd_unix throws segmentation fault

### ISSUE THREAD

**Issue by tami2293** [spel-uchile/SUCHAI-Flight-Software#4]
Command to reproduce
`fp_del_cmd_unix -117178099079143373510838603518012080043 218686494558336962698724816534476462258 12695751144231085238`

**Comment by keimi** [comment]
Command failing because implementation of 'flight plan' commands do not exist for st_mode 2 (postgres). 

The solution for the issue is to implement flight plan functions for postgres:

- storage_flight_plan_erase
- storage_flight_plan_get
- storage_flight_plan_set
- storage_flight_plan_show_table
